### ISSUE TITLE
Shelly can't run command with a relative path anymore

### ISSUE THREAD

**Issue by gdetrez** [gregwebs/Shelly.hs#107]
Using `cmd` or `run` with a relative path doesn't work anymore (it used to some version ago).
E.g.

``` hs
shelly (cmd "./foo")
```

**Comment by gregwebs** [comment]
Thanks for opening the bug. Not sure what changed to mess this up. I uploaded version 1.6.3.2

**Comment by gdetrez** [comment]
The new version doesn't seem to fix the problem. I still got an exception when trying to run a command with a relative path:
```
*Main Shelly> shelly $ cmd "./foo"
*** Exception: 
Ran commands: 
./foo
which ./foo

Exception: user error (shelly did not find ./foo in the PATH: ...)

*Main Shelly> shelly $ canonicalize "./foo" >>= cmd
Hello World
"Hello World\n"
```

**Comment by gdetrez** [comment]
It seems to be system dependent as it works on OS X (10.8.5) but not on fedora (22). (And since I didn't get the problem before, I suspect it worked on fedora 20 as well.)

I don't quite understand what is causing this but I found a subtle difference that might be relevant: when I try to run a command that does not exist, the error message is slightly different:

OS X
```
Shelly> shelly $ verbosely $ cmd "./fooo"
./fooo
*** Exception: 
Ran commands: 
echo './fooo'
./fooo
which ./fooo

Exception: error running: ./fooo
exit status: 127. exit code 127 usually means the command does not exist (in the PATH)
stderr: 
```

Fedora
```
Shelly> shelly $ verbosely $ cmd "./fooo"
./fooo
*** Exception: 
Ran commands: 
echo './fooo'
./fooo
which ./fooo

Exception: user error (shelly did not find ./fooo in the PATH: /home/gregoire/tmp/.cabal-sandbox/bin:/home/gregoire/.cabal/bin:/usr/local/bin:/usr/local/sbin:/usr/lib64/qt-3.3/bin:/usr/bin:/usr/sbin:/bin:/sbin:/home/gregoire/bin:/home/gregoire/.local/bin)
```

**Comment by gregwebs** [comment]
I don't think this should behave different on different OSs. Are you using the latest version of shelly on Fedora?

    :set -package shelly-1.6.3.2

**Comment by gdetrez** [comment]
Yes:
```
Prelude Shelly> :set -package shelly-1.6.3.2
package flags have changed, resetting and loading new packages...
Prelude Shelly> import Shelly
Prelude Shelly> shelly $ cmd "./fooo"
*** Exception: 
Ran commands: 
./fooo
which ./fooo

Exception: user error (shelly did not find ./fooo in the PATH:
