### ISSUE TITLE
doesn't work on Windows any more

### ISSUE THREAD

**Issue by hsenag** [gregwebs/Shelly.hs#176]
Since commit 94acbcce02312749df125968e3c01adabcf77df8, shelly depends on 'unix' so doesn't build on Windows any more. Is this intentional? @rocketnik

**Comment by nikolas-mayr-deliveryhero-github** [comment]
Sorry, my fault. No it is not. Will fix it in the next days.

**Comment by rocketnik** [comment]
Sorry, my fault. No it is not. Will fix it in the next days.

**Comment by hsenag** [comment]
No problem, thanks. It's unusable anyway thanks to #177, but one step at a time :-)

**Comment by leohaskell** [comment]
Please downgrade the version in [LTS](https://www.stackage.org/lts). LTS shouldn't contain packages that can't be compiled.

**Comment by mihaimaruseac** [comment]
Shelly downgraded in LTS 13.4 to 1.8.0

**Comment by ozgurakgun** [comment]
Hijacking this issue, please let me know if you prefer a new issue.

- [1.8.0](http://hackage.haskell.org/package/shelly-1.8.0) did not depend on unix, and I was using it on Windows.
- [1.8.1](http://hackage.haskell.org/package/shelly-1.8.1) now depends on unix, and hence doesn't build on Windows.

Was this on purpose? Can it be avoided?

**Comment by gregwebs** [comment]
It would be great to have a Windows use submit a fix for this

**Comment by hsenag** [comment]
I did look into it a bit when I first ran into this, and I can't remember exactly what I found, but I don't think it was easy. Just rolling back the change that introduced the unix dependency is my only real suggestion.

**Comment by gregwebs** [comment]
Can you send a tested pull request?

**Comment by hsenag** [comment]
Are you happy with the principle of rolling back the change? If so I'll do it when I have a chance, might not be immediately.

**Comment by gregwebs** [comment]
Sounds good to me

**Comment by andreasabel** [comment]
Could this issue be solved by using `unix-compat` instead of `unix`?

**Comment by andreasabel** [comment]
I think this is fixed.  Please reopen with new information if you disagree.
