### ISSUE TITLE
build failure with base < 4.9

### ISSUE THREAD

**Issue by hvr** [gregwebs/Shelly.hs#188]
As can be observed at 

https://matrix.hackage.haskell.org/package/shelly@1567109168

despite advertising compatibility with base-4.9 and older, `shelly-1.9.0` failed to build in those build configurations. I already revised the metadata via

http://hackage.haskell.org/package/shelly-1.9.0/revisions/

to reflect the requirements more accurately so that cabal won't be running into this invalid build plans; the result of which can be observed at

https://matrix.hackage.haskell.org/package/shelly@1567491748

please take this into account for future `shelly` releases.

**Comment by andreasabel** [comment]
This is fixed.
