### ISSUE TITLE
Cannot run program that expects input like ghci and fzf

### ISSUE THREAD

**Issue by mingyuguo** [gregwebs/Shelly.hs#195]
If I do cmd "ghci abc.hs", what I see is that ghci launched and abc.hs successfully loaded, but then ghci immediately exists (I am assuming that's because it detects that "cmd" no longer sends anything to stdin.

Similarly, cmd "fzf" will not show anything. 
cmd "xterm -e fzf" will work though.

**Comment by andreasabel** [comment]
Maybe you find a suitable function in module `System.Process`: https://hackage.haskell.org/package/process-1.6.13.2/docs/System-Process.html
