### ISSUE TITLE
Hackage has version 1.9.0 but the newest version here on github is 1.8.0

### ISSUE THREAD

**Issue by ddssff** [gregwebs/Shelly.hs#199]
Is this not the official repository?

**Comment by andreasabel** [comment]
Yes, it is!

**Comment by andreasabel** [comment]
Well, it seems some changes got lost.
E.g., the repo has no commits between 2019-06-17 and 2019-09-30, but 1.9.0 was uploaded to hackage on 2019-08-29:
> Uploaded | by GregWeber at 2019-08-29T20:06:08Z

So it is unclear where to place the tag `v1.9.0` in this repo.
