### ISSUE TITLE
Does this package have an active maintainer?

### ISSUE THREAD

**Issue by andreasabel** [gregwebs/Shelly.hs#202]
Does this package have an active maintainer?

The last commit is 11 month ago, there are a few PRs now that have not seen a review after half a year.
Ping @gregwebs.

**Comment by gregwebs** [comment]
Sorry I missed the PRs. I would be happy to have a new maintainer of this package.

**Comment by andreasabel** [comment]
@gregwebs: I am happy to be added as a co-maintainer, to help out with administrative issues, merging PRs, releases to cope with an evolving ecosystem (like new GHCs), etc.  However, I would not work on improving the package itself.
If this is useful to you, please add me here and on hackage.

**Comment by gregwebs** [comment]
@andreasabel thanks, I invited you

**Comment by andreasabel** [comment]
@gregwebs : Thanks!
You did not add me on hackage yet: https://hackage.haskell.org/package/shelly/maintainers/
Is this an oversight?

**Comment by andreasabel** [comment]
Ping @gregwebs: please also add me on hackage.

**Comment by gregwebs** [comment]
@andreasabel sorry I missed your message. You are added on Hackage now.
