### ISSUE TITLE
"Shellish" behaviour on Mac OS X 10.8 and GHC 7.6.3

### ISSUE THREAD

**Issue by adinapoli** [gregwebs/Shelly.hs#35]
Hello guys,

in the past (I'm the guy of the "Testimonials" link) I've used Shelly without problems (Linux and GHC 7.4, I'm pretty sure), but now on Mac OS X 10.8 and GHC 7.6.3 I'm experiencing the old Shellish behaviour, namely the output is visible only after the command has been completed. To demostrate this (at least on my particular environment) I've whipped up this small program:

``` haskell
{-# LANGUAGE OverloadedStrings #-}
import Shelly
import Data.Text as T
import Data.Monoid

cabal :: [Text] -> Sh Text
cabal = run "cabal"

sandboxCreation :: Sh Text
sandboxCreation = undefined

main :: IO ()
main = shellyNoDir . verbosely $ do
    echo $ toTextArg "This will be printed immediately"
    initResult <- cabal ["update"]
    sandboxCreation
    echo "Finished! Now let's hack some Haskell!"
```

What happens is that the echo is printed immediately, whilst the program remain "stuck" on cabal update for a while, and then it print in "burst":

```
Downloading the latest package list from hackage.haskell.org
Main.hs:
Ran commands:
echo 'This will be printed immediately'
echo 'cabal update'
cabal update

Exception: Prelude.undefined
```

My first thought was that something changed codewise since I've used Shelly, or it's the platform/ghc version to do the difference.
Any idea?

Thanks!
A.

**Comment by andreasabel** [comment]
Seems like this problem resolved itself.  Maybe it was in some dependency or in GHC.  
The first GHC that works e.e. with macOS 10.14 is 7.8.
